In [1]:
import numpy as np
data=np.random.randn(2,3)#creat random data
print(data)
data*10
print(data)
data+=data
print(data)

[[-1.35023934  0.51345515 -0.91654652]
 [ 0.99676861 -1.7391544  -0.13385248]]
[[-1.35023934  0.51345515 -0.91654652]
 [ 0.99676861 -1.7391544  -0.13385248]]
[[-2.70047868  1.0269103  -1.83309305]
 [ 1.99353722 -3.4783088  -0.26770497]]


In [2]:
#创建数组   数据是同一类型的
data1=[6,7,8,0,1]
arr1=np.array(data1)   #in creation ，able self define dtype=np.float64   ,show 64bit=8bite
print(arr1)

[6 7 8 0 1]


In [3]:
data2=[[1,2,3,4],[5,5,6,7]]  
#数据结构一致，长度也要一致
arr2=np.array(data2)
print(arr2)
print(arr2.shape)  #内部数据的尺度 2*4的一个数组，当两行4列吧
print(arr2.dtype)   #auto give type
print(arr2.ndim)    #two lines


[[1 2 3 4]
 [5 5 6 7]]
(2, 4)
int32
2


In [58]:
arr3=np.zeros(10)
print(arr3)  #creat all 0
arr4=np.empty((2,3,2)) #return value not all 0 but grabage   multi dimention 
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[6.23042070e-307 4.67296746e-307]
  [1.69121096e-306 1.33508760e-307]
  [1.89146896e-307 7.56571288e-307]]

 [[3.11525958e-307 1.24610723e-306]
  [1.29061142e-306 1.33514617e-307]
  [1.06806669e-306 8.45603441e-307]]]


array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [5]:
list1=np.arange(10) #相同于内部的range函数
print(list1)


[0 1 2 3 4 5 6 7 8 9]


In [6]:
arr5=np.array(list1,dtype=np.int64)  #able define in your selfves
print(arr5.dtype)
print(arr5)

int64
[0 1 2 3 4 5 6 7 8 9]


In [7]:
arr=np.array([3.7,-1.2,-2.6,0.5,12.9])
arr
arr.astype(np.int32)  #enforce cutdown after point part

array([ 3, -1, -2,  0, 12])

In [8]:
numeric_strings=np.array(['1.25','-9.6','-1.56'])
numeric_strings.astype(float)   #float or np.float32 able allow  because Numpy  map to np.float32  


array([ 1.25, -9.6 , -1.56])

In [9]:
int_array=np.arange(10)
calibers=np.array([.25,-9.630,.568,.588])
int_array.astype(calibers.dtype)
#transfer the same dtype to 'calibers'

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
#able use simple type like u4
empty_uint32=np.empty(8,dtype='u4')
empty_uint32


array([    0,     1,     0,   634,   380,     0,   768, 32762],
      dtype=uint32)

In [11]:
# Use astype to copy the old array to a new one
#in bottom layer,astype do this
#calculate array
arr1*arr1 # Multiply elements in the same position
arr6=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr6*arr6## Same position means the indices are exactly the same


array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [12]:
#arr compute will work in every elements
1/arr6


array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111]])

In [13]:
arr7=np.array([[0.,4.,1.],[7,2,12],[5,3,1]],dtype=np.float64)
arr7
# Compare arrays: when shapes are the same, will create a boolean array
arr7>arr6


array([[False,  True, False],
       [ True, False,  True],
       [False, False, False]])

In [14]:
result=arr7>arr6
result.dtype

dtype('bool')

In [15]:
#Indexing an array,Slicing an array
arr8=np.arange(10)
arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr8[5]  #indexing 

5

In [17]:
arr8[5:8]

array([5, 6, 7])

In [18]:
arr8[5:8]=12#不同于列表 列表切片是放到一个新列表,数组切片是对原数组的切片 所有值都修改
arr8

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [19]:
arr_slice=arr8[5:9]
arr_slice

array([12, 12, 12,  8])

In [20]:
arr8

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [21]:
arr_slice[1]=12345
arr8   ## Changes will be reflected in the original

arr_slice[:]=64#will assign all arr
arr_slice

array([64, 64, 64, 64])

In [22]:
arr8

array([ 0,  1,  2,  3,  4, 64, 64, 64, 64,  9])

In [23]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [24]:
#two ways can get the elements in 2D array
#arr2d[0][2]  or arr2d[0,2]
arr2d[2,2]

9

In [25]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
old_values=arr3d[0].copy()
arr3d[0,:]#arr3d the first arr's  all element
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
arr3d[0]=old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

返回的数组都是视图”是指在 NumPy 中，当你对一个数组进行切片或索引操作时，返回的结果是原数组的一部分视图，而不是一个新的独立数组

In [29]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr2d[:2]#  行切  每个数组就是一行  比如a[0]  就是第一行，沿着行切就是第0轴  表示切到第二行 不包括第二行

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
#可以传入多个切片，就像传多个索引
arr2d[:2,1:]   #同理，切到第二列，不包括第二列

array([[2, 3],
       [5, 6]])

In [32]:
arr2d[:,:2]


array([[1, 2],
       [4, 5],
       [7, 8]])

In [33]:
arr2d[1,:2]

array([4, 5])

In [34]:
arr2d[:2,2]#左行/右列

array([3, 6])

In [35]:
arr2d[:,:1]#

array([[1],
       [4],
       [7]])

In [36]:
#布尔型索引
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)#
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

data = np.random.randn(7, 4) 这行代码使用 NumPy 生成一个形状为 
7×4 的二维数组，其中包含从标准正态分布（均值为0，标准差为1）中生成的随机数。


In [37]:
data

array([[ 0.62707085, -1.28322932, -0.92254654, -0.01006598],
       [ 1.40991197, -1.0224488 , -0.73919911,  1.07243445],
       [ 0.61868373,  0.04793338,  0.18859366,  0.77221373],
       [ 0.46480998,  0.07487675, -1.30819695,  1.14448516],
       [ 0.55366376, -1.80880966,  0.55466938,  0.94200297],
       [ 1.61049891, -0.11134448, -0.11806394, -0.80447537],
       [-1.5866077 ,  1.16552513,  1.26756666,  2.21127999]])

想选出对应与Ace开头的所有行，对names和字符串D开头的比较运算将会产生一个布尔数组
提到的“矢量化”是指在 NumPy 中对数组进行操作时，操作会自动应用到数组的每一个元素上，而不需要显式地编写循环。


In [38]:
names=='Bob'  #会创建一个布尔类型的数组


array([ True, False, False,  True, False, False, False])

In [39]:
#生成的布尔类型数组能用于数组的索引  布尔型数组的长度要跟被索引的轴长度一致   (行)
data[names=='Bob']

array([[ 0.62707085, -1.28322932, -0.92254654, -0.01006598],
       [ 0.46480998,  0.07487675, -1.30819695,  1.14448516]])

In [40]:
data[names=='Bob',2:]

array([[-0.92254654, -0.01006598],
       [-1.30819695,  1.14448516]])

In [41]:
data[names!='Bob',2:]

array([[-0.73919911,  1.07243445],
       [ 0.18859366,  0.77221373],
       [ 0.55466938,  0.94200297],
       [-0.11806394, -0.80447537],
       [ 1.26756666,  2.21127999]])

In [42]:
data[~(names!='Bob'),2:]

array([[-0.92254654, -0.01006598],
       [-1.30819695,  1.14448516]])

In [43]:
mask = (names == 'Bob') | (names == 'Will')
data[mask]#可以用多个布尔条件运算符 不能用and 和or 而是&和|
#通过布尔类型索引的数据，总是创建数据的副本，即使返回一模一样的原数组，也是副本，看看对副本的修改是否会影响原数组的数据

array([[ 0.62707085, -1.28322932, -0.92254654, -0.01006598],
       [ 0.61868373,  0.04793338,  0.18859366,  0.77221373],
       [ 0.46480998,  0.07487675, -1.30819695,  1.14448516],
       [ 0.55366376, -1.80880966,  0.55466938,  0.94200297]])

In [44]:
r=data[names=='Bob',:]


In [45]:
r[:]=0
r

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
data

array([[ 0.62707085, -1.28322932, -0.92254654, -0.01006598],
       [ 1.40991197, -1.0224488 , -0.73919911,  1.07243445],
       [ 0.61868373,  0.04793338,  0.18859366,  0.77221373],
       [ 0.46480998,  0.07487675, -1.30819695,  1.14448516],
       [ 0.55366376, -1.80880966,  0.55466938,  0.94200297],
       [ 1.61049891, -0.11134448, -0.11806394, -0.80447537],
       [-1.5866077 ,  1.16552513,  1.26756666,  2.21127999]])

In [47]:
#可以在索引内部 添加布尔类型，进行批量修改数据
data[data<0]=0  #将其中负值赋值为0
data

array([[0.62707085, 0.        , 0.        , 0.        ],
       [1.40991197, 0.        , 0.        , 1.07243445],
       [0.61868373, 0.04793338, 0.18859366, 0.77221373],
       [0.46480998, 0.07487675, 0.        , 1.14448516],
       [0.55366376, 0.        , 0.55466938, 0.94200297],
       [1.61049891, 0.        , 0.        , 0.        ],
       [0.        , 1.16552513, 1.26756666, 2.21127999]])

In [48]:
#花式索引 Fancy indexing  
#利用整组数组进行索引
arr9=np.empty((8,4),dtype=int)   #传参数是传一个元祖  8行4列
arr9

array([[ -494942990,  1071911158,  1992265582,  1072990235],
       [ 1406745828,  1072530816,  1322893238,  1065655673],
       [ -722863837,  1071893569,  2078002546,  1068010169],
       [ 1398338702,  1070080982, -1860286852,  1072215545],
       [ 1489642595,  1071497074,  1513041541,  1068706591],
       [ -317941542,  1073016415, -1431536033,  1072844751],
       [  302578116,  1071757213,  1702927860,  1073541346],
       [   41114480,  1071759322,  1750803750,  1072571619]])

In [49]:
for i in range(8):   #一一赋值
    arr9[i]=i
arr9      

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

In [50]:
#为了选取特定顺序选取行子集，只需传入用于指定顺序的整数列表或者ndarrary
arr9[[4,3,0,6]]   #传入列表，而不是单独的数字   重新排序了


array([[4, 4, 4, 4],
       [3, 3, 3, 3],
       [0, 0, 0, 0],
       [6, 6, 6, 6]])

In [51]:
#或者使用负数从后面开始索引
#切片切出来的都是映射，索引出来的模板，花式索引和切片不同，索引总是将数据复制到新数组中
arr9[[-3,-5,-7]]#语法上区别  []  里面的索引是加括号的


array([[5, 5, 5, 5],
       [3, 3, 3, 3],
       [1, 1, 1, 1]])

In [52]:
#转置  ，返回到是原数据视图，不会进行任何赋值，不仅有transpose，还有T属性
arr10=np.arange(15).reshape(3,5)  #arange同for i inrange
#.reshape方法重塑   怎么重塑： 按行排下来
arr10

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [53]:
arr10.T  #转置变成三列五行

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [54]:
#矩阵内积计算  np.dot
arr=np.random.randn(3,3)  #包含从标准正态分布（均值为0，标准差为1）中随机抽取的数值
np.dot(arr,arr.T)

array([[ 2.80029772, -0.4046237 , -1.7347908 ],
       [-0.4046237 ,  0.14766379, -0.40854314],
       [-1.7347908 , -0.40854314,  5.94933314]])

In [55]:
arr=np.arange(9).reshape(3,3)
np.dot(arr,arr)


array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [56]:
#对于高维数组，需要得到一轴编号组成的元组，才能对这些轴进行转置
arr=np.arange(16).reshape((2,2,4))#定义三维数组 两行两列 四高
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [57]:
arr.transpose((1,0,2))  #换了行的顺序  第一个位置放轴1  第二个位置轴0   第三个位置轴2  ，简单转置可用.T方式
arr.swapaxes(1,2)#也是源视图，而不是复制到新数组  作用是交换轴1和轴2    类似转置  横变竖   不会进行任何复制操作

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])