通用函数（即ufunc）是一种对ndarray中的数据执行元素级运算 的函数。你可以将其看做简单函数（接受一个或多个标量值，并 产生一个或多个标量值）的矢量化包装器。

In [1]:
import numpy as np

arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x=np.random.randn(8)
y=np.random.randn(8)
x

array([-0.24464714, -1.56672474, -0.25979959,  0.45858723, -1.24503829,
       -0.12270236,  0.03227224,  0.17306566])

In [7]:
y

array([ 1.17926258,  0.58414903, -0.55714629,  3.10630587, -0.4928988 ,
        2.36850387,  0.57701523, -1.02126024])

In [8]:
np.maximum(x,y)  #对应下标位置 选数值大的  选出

array([ 1.17926258,  0.58414903, -0.25979959,  3.10630587, -0.4928988 ,
        2.36850387,  0.57701523,  0.17306566])

In [10]:
np.minimum(x,y)


array([-0.24464714, -1.56672474, -0.55714629,  0.45858723, -1.24503829,
       -0.12270236,  0.03227224, -1.02126024])

In [13]:
arr=np.random.randn(7)*5
arr

array([-11.31485964,  -6.71184374,   1.55168209,  -2.51914703,
        -1.4875914 ,  -3.00720123,  -0.85246556])

In [14]:
remainder,whole_part=np.modf(arr)#将数组中的整数和小数部分分开
remainder


array([-0.31485964, -0.71184374,  0.55168209, -0.51914703, -0.4875914 ,
       -0.00720123, -0.85246556])

In [15]:
whole_part

array([-11.,  -6.,   1.,  -2.,  -1.,  -3.,  -0.])

Ufuncs接受out选项，可以让他们在数组的原地进行操作
arr


In [16]:
arr

array([-11.31485964,  -6.71184374,   1.55168209,  -2.51914703,
        -1.4875914 ,  -3.00720123,  -0.85246556])

In [18]:
np.sqrt(arr)


C:\Users\73835\AppData\Local\Temp\ipykernel_28128\1870496444.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan,        nan, 1.24566532,        nan,        nan,
              nan,        nan])

In [19]:
np.sqrt(arr,arr)  #这个就是接受了out ，out回原数组输出

C:\Users\73835\AppData\Local\Temp\ipykernel_28128\420847243.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr,arr)


array([       nan,        nan, 1.24566532,        nan,        nan,
              nan,        nan])

In [20]:
arr

array([       nan,        nan, 1.24566532,        nan,        nan,
              nan,        nan])

一元ufunc
函数
abs, fabs
计算整数、浮点数或复数的绝对值。对于非复数值，可以使用更快的fabs。
sqrt
计算各元素的平方根。相当于arr ** 0.5。
square
计算各元素的平方。相当于arr ** 2。
exp
计算各元素的指数e。
log, log10, log2, log1p
计算自然对数（底数为e）、底数为10的log、底数为2的log、log(1 + x)。
sign
计算各元素的正负号：1（正数）、0（零）、-1（负数）。
ceil
计算各元素的ceiling值，即大于等于该值的最小整数。
floor
计算各元素的floor值，即小于等于该值的最大整数。
rint
将各元素值四舍五入到最接近的整数，保留dtype。
modf
将数组的小数和整数部分以两个独立数组的形式返回。
isnan
返回一个表示“哪些值是NaN（这不是一个数字）”的布尔型数组。
isfinite, isinf
分别返回一个表示“哪些元素是有穷的（非inf, 非NaN）”或“哪些元素是无穷的”的布尔型数组。
cos, cosh, sin, sinh, tan, tanh
普通型和双曲型三角函数。
表4-3：一元ufunc（续）
函数
arccos, arccosh, arcsin, arcsinh, arctan, arctanh
反三角函数。
logical_not
计算各元素not的真值。相当于-arr。