两个主要的函数
np.save()
和np.load()

In [1]:
import numpy as np

arr=np.arange(10)
np.save('some_array',arr)#没拓展名自动会加 

In [5]:
np.load('some_array.npy')


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#np.savez  可以将多个数组保存到一个未压缩文件中，以关键字形式传入进去
np.savez('array_archive.npz',a=arr,b=arr)
#得到类似字典的对象  加载的时候
arch=np.load('array_archive.npz')


In [7]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

numpy.savez_compressed。numpy.savez_compressed 本身就是一个用于压缩和保存 NumPy 数组的函数。你只需要直接使用这个函数，它会自动对数据进行压缩并保存为 .npz 文件。

In [14]:
np.savez_compressed('arraycompressed.npz',a=arr,b=arr)
arc=np.load('arraycompressed.npz')
arc['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])