线性代数（如矩阵乘法、矩阵分解、行列式以及其他方阵数学 等）是任何数组库的重要组成部分。

In [72]:
import numpy as np

#点积
x=np.arange(0,2)
y=np.arange(2,4)
x

array([0, 1])

In [73]:
y

array([2, 3])

In [74]:
np.dot(x,y.T)   #一维数组，转置与否，结果不会有不同。二维数组转置就有关了 ，属于矩阵运算了


3

In [75]:
x = np.array([[0, 1], [2, 3]])  # 2x2 矩阵
y = np.array([[2, 3], [4, 5]])  # 2x2 矩阵

np.dot(x,y)

array([[ 4,  5],
       [16, 21]])

In [76]:
np.dot(x,y.T)#  可以是矩阵运算，也可是点积，取决于数组的维度


array([[ 3,  5],
       [13, 23]])

In [77]:
x.dot(y)#等价于np.dot(x,y)


array([[ 4,  5],
       [16, 21]])

np.dot 函数接受两个参数，第一个参数是左边的向量，第二个参数是右边的向量。

x 是调用 dot 方法的对象，所以它在左边。

In [78]:
x = np.array([[1, 2], [3, 4]])
y = np.ones(2)  # 调整为形状 (2,)  用于创建一个全是1的数组或者矩阵
np.dot(x, y)

array([3., 7.])

In [79]:
x@y   #用x@y也是同样的效果  矩阵乘法


array([3., 7.])

In [80]:
#提供了一系列方法 用于求逆和行列式  需要导入numpy.linalg中的inv qr

X=(np.random.randn(3,3))

mat=X.T.dot(X)
mat

array([[ 2.51880117, -0.15452613,  0.17855984],
       [-0.15452613,  3.46498028,  1.21220604],
       [ 0.17855984,  1.21220604,  0.52185467]])

In [81]:
from numpy.linalg import inv,qr

mat_inv=inv(mat)
mat_inv



array([[ 0.51060804,  0.44778495, -1.21486255],
       [ 0.44778495,  1.93311861, -4.64361933],
       [-1.21486255, -4.64361933, 13.11849715]])

In [83]:
product=mat.dot(mat_inv)  #inv用于计算逆矩阵  需要确保方阵可逆  
product

array([[ 1.00000000e+00, -2.55136518e-17,  4.29407788e-16],
       [-2.36142348e-16,  1.00000000e+00,  4.56417649e-15],
       [-1.27189192e-17,  1.10317875e-16,  1.00000000e+00]])

In [85]:
q,r=qr(product)  #Q是正交阵，R是上三角矩阵， qr分解 能将矩阵进一步分解
q

array([[-1.00000000e+00, -2.36142348e-16,  1.27189192e-17],
       [ 2.36142348e-16, -1.00000000e+00, -1.10317875e-16],
       [ 1.27189192e-17, -1.10317875e-16,  1.00000000e+00]])

In [86]:
r

array([[-1.00000000e+00,  2.61655999e-16, -4.16688868e-16],
       [ 0.00000000e+00, -1.00000000e+00, -4.67449436e-15],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

# 表 4-7：常用的 numpy.linalg 函数

函数  说明
-----  ------
diag  以一维数组的形式返回方阵的对角线（或非对角线）元素，或将一维数组转换为方阵（非对角线元素为0）
dot   矩阵乘法
trace 计算对角线元素的和
det   计算矩阵行列式
eig   计算方阵的本征值和本征向量
inv   计算方阵的逆
pinv  计算矩阵的 Moore-Penrose 伪逆
qr    计算 QR 分解
svd   计算奇异值分解（SVD）
solve 解线性方程组 Ax = b，其中 A 为一个方阵
lstsq 计算 Ax = b 的最小二乘解
