numpy.random对random增加了补充  


In [3]:
import numpy as np

sample=np.random.normal(size=(4,4))#生成4*4的样本数组，且均服从正态分布  normal  生成4*4的正态分布矩阵
sample

array([[-1.21171021, -1.49696024, -1.20065492, -0.23897707],
       [ 0.15801672,  0.46424019, -1.59845205,  1.07720435],
       [-0.43404653,  2.02426939, -2.03551163, -1.31379788],
       [ 0.33483534,  0.64608005, -0.56132573,  0.30055255]])

In [4]:
from random import normalvariate
import timeit

# 定义N的值
N = 1000000

# 使用列表推导生成正态分布随机数
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

# 使用NumPy生成正态分布随机数
%timeit np.random.normal(size=N)

#可见时间相差十几倍


471 ms ± 11.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
14.3 ms ± 237 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
#这些随机数 都是基于随机数生成中字，在确定性条件下生成的，使用NumPy可更改随机数生成种子只需要在开始生成随机数之前设置一次种子，然后生成的所有随机数都是这个种子对应的确定序列的一部分。如果你需要在不同的地方生成相同的随机数序列，可以在每次生成之前重新设置种子
ran=np.random.seed(1234)
sample=np.random.normal(size=(4,4))
sample

array([[ 4.71435164e-01, -1.19097569e+00,  1.43270697e+00,
        -3.12651896e-01],
       [-7.20588733e-01,  8.87162940e-01,  8.59588414e-01,
        -6.36523504e-01],
       [ 1.56963721e-02, -2.24268495e+00,  1.15003572e+00,
         9.91946022e-01],
       [ 9.53324128e-01, -2.02125482e+00, -3.34077366e-01,
         2.11836468e-03]])

In [17]:
ran=np.random.seed(1234)  #设置种子，种子相同，值也就定下来了
random_numbers = np.random.rand(5)
random_numbers

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581])

In [16]:
ran=np.random.seed(1234)
random_numbers = np.random.rand(5)
random_numbers

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581])

In [18]:
#避免全局随机种子，可以用numpy.random.RandomState 创建局部的随机数生成器
rng=np.random.RandomState(1234)
rng.randn(10)


array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

表4-8：部分numpy.random函数

函数       说明
seed       确定随机数生成器的种子
permutation 返回一个序列的随机排列或返回一个随机排列的范围
shuffle    对一个序列就地随机排列
rand       产生均匀分布的样本值
randint    从给定的上下限范围内随机选取整数
randn      产生正态分布（平均值为0，标准差为1）的样本值，类似于MATLAB接口
binomial   产生二项分布的样本值
normal     产生正态（高斯）分布的样本值
beta       产生Beta分布的样本值

表4-8：部分numpy.random函数（续）

函数       说明
chisquare  产生卡方分布的样本值
gamma      产生Gamma分布的样本值
uniform    产生在[0, 1)中均匀分布的样本值
